# Generated by Django 5.2.3 on 2025-06-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='defaut@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
